module.exports = {
    dainikSavera: [],
    guardian: ['/audio/', '/gallery/', '/video/', '/live/'],
    rBharat: [],
    rediff: ['liveupdates.htm', '/slide-show/', '/report/'],
    bbcHindi: ['/podcasts/', '/live/', '/topics/', '/academy/', 'extra', '/media-', '/resources/'],
    freePressJournal: ['/ampstories/', "/weekend/", "science", "//marathi", "/horoscope", "/interviews", "-reviews", "lifestyle"],
    timesNowNews: ['/videos/', '/short-videos/', '/web-stories/', '/recipes/', '-liveblog-', '/reviews/'],
    theIndianExpress: [],
    indiaTodayMagazine: [],
    economist: [],
    news24: [],
    gujOneIndia: [],
    theTribune: [],
    timesOfIndia: [],
    indiaToday: [],
    aniNews: [],
    independent: [],
    zeeNews: [],
    zeeBusiness: [],
    ndtv: ['/video/'],
    NavgujaratSamay: ['/categoryNews/', '/news/'],
    indiaTvNews: [],
    news18: [],
    theHindu: ['/cartoon/'],
    mintNews: [],
    hindustanTimes: ['/videos/', '/shop-now/'],
    foxNews: [],
    amarUjala: ['/photo-gallery/', '/video-shots/', '/web-stories/', '/podcast/', '/video/', '/audios/'],
    cnnNews: ['/videos/', '/collections/', '/style/', '/live-news/'],
    jagranJosh: [],
    pib: [],
    navBharat: ['/photo/','/photos/'],
    midDay: [],
    businessStandard: ['/markets/', '/current-affairs/', '/content/'],
    skyNews: [],
    dainikBhaskar: [],
    samacharJagat: [],
    divyaBhaskar: [],
    theShillongTimes: [],
    cbsNews: ['/video/'],
    gujaratSamachar: [],
    gujaratiNews18: ['/photogallery/', '/videos/'],
    nyTimes: ['/live/'],
    ddNews: [],
    punjabKesari: [],
    sanmarg: [],
    aljazeera: ['/liveblog/', '/longform/'],
    dailyPioneer: [],
    deccanHerald: ['/video/', '-live-'],
    reuters: [],
    millenniumPost: [],
    theFinancialExpress: [],
    mumbaiSamachar: [],
    prajavani: ['/podcast/', '/video/', '/photo/'],
    jansatta: [],
    bbcNews: ['/live/', '/reel/'],
    theNavhindTimes: [],
    pingiiit: [],
    telegraph: [],
    totalTv: [],
    aajKaalDaily: [],
    jaiHind: [],
    sanjSamachar: [],
    sandesh: ['javascript:void(0)'],
    punjabiJagran: ['/web-stories/'],
    eastMojo: [],
    gujaratMitra: [],
    iAmGujarat: ['/web-stories/','/photogallery/','/videos/'],
    vishwavani: [],
    rashtraDeepika: [],
    nobat: [],
    gujaratiEconomicTimes: [],
    ptiNews: ['/factcheck/'],
    siliconIndia: ['/magazine/', '/viewpoint/', 'blogs.siliconindia.com', '/magazine_articles/', '/travel-article/'],
    theHansIndiaTelugu: [],
    theHansIndia: ['/movie-reviews/'],
    zeeTamil: ['/photo-gallery/'],
    westernTimes: [],
    aajtak: ['/interactive/', '/visualstories/','/video/','/short-videos/'],
    news18Lokmat: [],
    cnbcTv18: ['/photos/'],
    etNow: ['/videoshow/', '/web-stories/', '/slideshow/', '/primeshots/', '/live-blog/', '-live-', '/blogs/'],
    varthaBharathi: ['/gallery/', '/video/'],
    urduNews18: ['/photogallery/', '/videos/'],
    odiaNews18: ['/photogallery/', '/videos/'],
    assamNews18: ['/photogallery/', '/videos/'],
    chitralekha: ['/ticker/'],
    telegraphIndia: ['photogallery'],
    manoramaOnline: ['/news/latest-news.html'],
    kannadaNews18: ['/photogallery/', '/videos/', '-live-updates-'],
    keralaNews18: ['/photogallery/', '/videos/'],
    banglaNews18: ['/photogallery/', '/videos/'],
    gujaratiWebdunia: [
      '/about-hinduism/',
      '/vastu-tips/',
      '/gujarati-health-tips/',
      '/gujarati-beauty-tips/',
      '/gujarati-vegetarian-food/',
      '/gujarati-more-jokes/',
    ],
    dnaIndia: [],
    theStatesmanEnglish: [],
    kutchUday: [],
    trinityMirror: [],
    deccanChronicle: ['/javascript:void(0);', '/most-popular'],
    akila: [],
    news18rajasthan: ['/photogallery/', '/videos/'],
    andhraHeadlines: ['gallery-'],
    naiDunia: [],
    theSentinel: ['/horoscope/', '/videos/'],
    gujaratiMidday: ['/photo/'],
    sakal: ['-live-', '/video-story/'],
    kutchmitraDaily: [],
    hariBhoomi: [],
    frontline: [],
    northEastTimes: [],
    assamTribune: ['/video/'],
    odishaTV: ['/astrospeak/', '/photo-gallery/'],
    theSangaiExpress: [],
    bharatTimes: [],
    greaterKashmir: ['/videos/'],
    hinduBusinessLine: ['/cartoons/'],
    firstPost: ['/photos/','/tech/'],
    lokmat: [],
    abpNews: ['/photo-gallery/', '/videos/'],
    maharashtraTimes: ['/video/', '/liveblog/', '/web-stories/', '/videoshow/', '/photogallery/'],
    malayalaManorama: [],
    mathrubhumi: ['/videos/', '/stat/'],
    uttarakhandNewsNetwork: [],
    newsNationTv: ['/visual-stories/', '/videos/', '/photos/'],
    northeastNow: [],
    mumbaiMirror: ['/photos/', '/photostory/'],
    openMagazine: [],
    punjabNews18: ['/photogallery/','/videos/'],
    oneindia: [],
    republicWorld: ['imageid-1', 'liveblog','/the-debate/'],
    pinkVilla: [],
    scrollIn: ['/video/'],
    samachar: [],
    theBetterIndia: [],
    theIndianWire: [],
    theNewIndianExpress: ['/videos/','/galleries/'],
    samayam: ['/liveblog/', '/photo-gallery/'],
    thePrint: [],
    theLogicalIndian: ['/videos/'],
    theQuint: ['video', '/collection/'],
    tv9TeluguNews: ['/videos/', 'live-watch', 'video'],
    theWire: ['//science'],
    theWireHindi: [],
    indiaAbroad: ['/snapshots/'],
    vijayKarnataka: ['/video/', '/photoshow/', '/liveblog/', '/videoshow/'],
    punjabNewsExpress: [],
    indiaCom: [],
    ap7am: ['-live','-article-','pn-'],
    navbharatTimes: ['/web-stories/', '/visual-story/', '/photomazza/'],
    businessToday: ['/photo/', '/panorama/', '/video/'],
    deshGujarat: [],
    chandigarhNews: [],
    gujarat_samachar: [],
    kannadaPrabha: [],
    kashmirObserver: [],
    pardaPhash: [],
    southLive: ['/video-story/'],
    samayamTamil: ['/web-stories/','/photoshow/', '/liveblog/', 'live-updates-', '/photogallery/'],
    sportsKeeda: [],
    theNewsMinute: [],
    theSiasatDaily: [],
    theWeek: [],
    ujjawalPrabhat: [],
    udayavani: [],
    asianetNewsNetwork: ['/video/'],
    sikhSiyasat: [],
    dinamalar: [],
    webdunia: [],
    timesNowHindi: ['/videos/', "liveblog", "live-updates", '/reviews/'],
    samacharPlus: [],
    theStatesmanBengali: [],
    zeeSalaam: ['/photo-gallery', '/video/', '/web-stories/', '/live-updates/'],
    zeePunjabHaryanaHimachal: ['/photo-gallery','/web-stories/','/live-updates/'],
    hindiNews18: ['/videos/', '/photogallery/', '/podcast/'],
    eenadu: ['/videos/','/photos/','-women-'],
  };
  